# Generated by Django 4.2.14 on 2024-07-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XYZCompany",
            fields=[
                ("InternID", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "FirstName",
                    models.CharField(
                        default=None, max_length=255, verbose_name="First Name"
                    ),
                ),
                (
                    "LastName",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Last Name"
                    ),
                ),
                ("TeamID", models.IntegerField()),
                ("JoiningDate", models.DateField()),
                ("ManagerID", models.BigIntegerField()),
                ("Location", models.CharField(max_length=255)),
                ("Stipend", models.IntegerField()),
                ("PhoneNo", models.BigIntegerField()),
                ("Email", models.EmailField(max_length=254)),
            ],
        ),
    ]
