# Generated by Django 5.0.7 on 2024-07-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xyzcompany',
            old_name='Email',
            new_name='EmailID',
        ),
    ]
