# Generated by Django 5.0.7 on 2024-07-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_email_xyzcompany_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xyzcompany',
            name='Stipend',
            field=models.BigIntegerField(),
        ),
    ]
