# Generated by Django 4.2.7 on 2024-07-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_xyzcompany_stipend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xyzcompany',
            table='company_xyzcompany',
        ),
    ]
